server:
  port: 8082
spring:
  freemarker:
    suffix: .html
#  thymeleaf:
#    mode: HTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#    cache: false
#    prefix: classpath:/templates
#    suffix: .html
#    enabled: true
  resources:
    static-locations: classpath:/templates/
  datasource:
    username: root
    password: thinker
    url: jdbc:mysql://localhost:3306/test
   # url: jdbc:oracle:thin:@localhost:1521:ORCL
   # username: scott
    #password: tiger
    #driver-class-name: oracle.jdbc.OracleDriver
  redis:
    host: 192.168.0.119
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: -1
        max-wait: 3000s
        max-idle: 2
    timeout: 5000s

#mybatis相关配置
mybatis:
  type-aliases-package: cn.com.vo
  mapper-locations: classpath:mybatis/*.xml



